version: '3.8'

services: 
  python-backend:
    build: 
      context: backend/.
      dockerfile: Dockerfile
      pull: true
    container_name: python-backend
    ports: 
      - "8000:8000"
    
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - python-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'sleep 10 && certbot certonly --webroot -w /var/www/certbot --email rokiwh40000.infrastructure@gmail.com --agree-tos --no-eff-email -d ekg-assistant.rokosz.win && nginx -s reload'"
    depends_on:
      - nginx