version: '3.8'

services: 
  python-backend:
    build: 
      context: backend/.
      dockerfile: Dockerfile
      pull: true
    container_name: python-backend
    ports: 
      - "8000:8000"
    
